Repository smileidentity/web-client, pull requests merged in 2025-05, with the labels that each got.

#410 deprecates the legacy smart camera web and remove reference from embed
  CHANGELOG.md
  package-lock.json
  packages/embed/cypress/support/commands.js
  packages/embed/cypress/tests/back-button.cy.cjs
  packages/embed/cypress/tests/consent-granted.cy.cjs
  packages/embed/cypress/tests/document-verification.cy.cjs
  packages/embed/cypress/tests/enhanced-document-verification-dev.cy.cjs
  packages/embed/cypress/tests/enhanced-document-verification.cy.cjs
  packages/embed/cypress/tests/id-selection.cy.cjs
  packages/embed/cypress/tests/smartselfie-auth-new-design.cy.cjs
  packages/embed/package.json
  packages/embed/src/js/biometric-kyc.js
  packages/embed/src/js/doc-verification.js
  packages/embed/src/js/enhanced-document-verification.js
  packages/embed/src/js/smartselfie-auth.js
  packages/web-components/cypress/e2e/smart-camera-web-attribution.cy.js
Labels: Review effort 3/5

#411 This improves the tests to allow testing both iife and esm builds
  packages/web-components/cypress/e2e/smart-camera-web-agent-mode.cy.js
  packages/web-components/cypress/e2e/smart-camera-web-attribution.cy.js
  packages/web-components/cypress/e2e/smart-camera-web-back-press.cy.js
  packages/web-components/cypress/e2e/smart-camera-web-complete-flow.cy.js
  packages/web-components/cypress/e2e/smart-camera-web-hide-back-to-host.cy.js
  packages/web-components/cypress/e2e/smart-camera-web-hide-instructions.cy.js
  packages/web-components/cypress/e2e/smart-camera-web.cy.js
  packages/web-components/cypress/pages/capture-back-of-id-hide-attribution.html
  packages/web-components/cypress/pages/capture-back-of-id-navigation.html
  packages/web-components/cypress/pages/smart-camera-web-agent-mode.html
  packages/web-components/cypress/pages/smart-camera-web-complete-flow.html
  packages/web-components/cypress/pages/smart-camera-web-hide-instructions.html
  packages/web-components/cypress/pages/smart-camera-web.html
  packages/web-components/cypress/support/commands.js
Labels: Review effort 2/5

#415 Run prod build before deploy
  .github/workflows/deploy-staging.yml
  .github/workflows/deploy.yml
Labels: Review effort 1/5

#416 Bump version to 2.0.0
  .gitignore
  CHANGELOG.md
  example/package-lock.json
  example/package.json
  package-lock.json
  package.json
  packages/embed/package.json
  packages/smart-camera-web/package.json
  packages/web-components/package.json
  packages/web-components/src/components/selfie/.DS_Store
  packages/web-components/src/components/selfie/src/.DS_Store
  packages/web-components/src/components/signature-pad/package.json
Labels: Review effort 1/5

#418 Fix: deploy embed to v2
  .github/workflows/deploy-preview.yml
  .github/workflows/deploy.yml
  CHANGELOG.md
  example/main.js
  example/package-lock.json
  example/package.json
  package-lock.json
  package.json
  packages/embed/package.json
  packages/smart-camera-web/package.json
  packages/web-components/package.json
  packages/web-components/src/components/signature-pad/package.json
  previews/app/routes/products.$productName.tsx
  previews/sst.config.ts
Labels: Review effort 2/5

#422 Selfie UI quickfix 2
  packages/embed/cypress/support/commands.js
  packages/web-components/cypress/e2e/smart-camera-web-agent-mode.cy.js
  packages/web-components/cypress/e2e/smart-camera-web-back-press.cy.js
  packages/web-components/cypress/e2e/smart-camera-web-complete-flow.cy.js
  packages/web-components/cypress/e2e/smart-camera-web-hide-instructions.cy.js
  packages/web-components/cypress/e2e/smart-camera-web.cy.js
  packages/web-components/cypress/support/commands.js
  packages/web-components/src/components/selfie/src/selfie-capture-instructions/SelfieCaptureInstructions.js
  packages/web-components/src/components/selfie/src/selfie-capture/SelfieCapture.js
Labels: Review effort 2/5

#424 release: 2.0.2
  CHANGELOG.md
  example/package.json
  package.json
  packages/embed/package.json
  packages/smart-camera-web/package.json
  packages/web-components/package.json
  packages/web-components/src/components/signature-pad/package.json
Labels: Review effort 1/5

#427 fix embed url in preview app
  .github/workflows/deploy-preview.yml
  previews/app/routes/products.$productName.tsx
  previews/sst.config.ts
Labels: Review effort 2/5
